alias up='cd ..'
alias h='history'
alias timer="open /Applications/Timer.app"
alias cln="mv *.doc* ~/.Trash"
alias dog="open ~/Pictures/dogs/*"
alias browser="open /Applications/qutebrowser.app"
alias htop='sudo htop'

alias get='curl -OL'
alias g='grep -i'
alias lr='ls -hartl'                        
alias ll='ls -lahG'
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'
alias df='df -h'
alias du='du -h'
alias mkdir='mkdir -p'
alias ip='ifconfig | grep inet  | grep -v 127.0.0.1'
